# Use uma imagem base do Node.js
FROM node:14

# Cria e define o diretório de trabalho dentro do contêiner
WORKDIR /usr/src/tts-front

# Copia o arquivo package.json e package-lock.json (se existirem)
COPY package*.json ./

# Instala as dependências do projeto
RUN npm install

# Copia o restante do código-fonte para o diretório de trabalho do contêiner
COPY . .

# Expõe a porta em que o aplicativo está rodando
EXPOSE 3000

# Comando para iniciar o aplicativo quando o contêiner for iniciado
CMD ["node", "index.js"]
