service: serverless-animais
frameworkVersion: '3'

plugins:
  - serverless-esbuild

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    TBL_NAME: ${env:TBL_NAME}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TBL_NAME}"

functions:
  animaisPerdidos:
    handler: handler.handler
    events:
      - httpApi:
          path: /animais/perdidos
          method: get
  animaisEncontrados:
    handler: handler.handler
    events:
      - httpApi:
          path: /animais/encontrados
          method: get

package:
  include:
    - node_modules/aws-sdk/**

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: []
    target: 'node20'
    define: { 'require.resolve': undefined }
    platform: 'node'
    external: ['aws-sdk']
