service: vision
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: python3.9
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "rekognition:DetectFaces"
            - "rekognition:DetectLabels"
            - "s3:*"  
            - "bedrock:*"
          Resource: "*"
  httpApi:
    cors: true

functions:
  health:
    handler: handler.health_route
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description_route
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: handler.v2_description_route
    events:
      - httpApi:
          path: /v2
          method: get
  v1Vision:
    handler: handler.v1_vision_route
    events:
      - httpApi:
          path: /v1/vision
          method: post
  v2Vision:
    handler: handler.v2_vision_route
    timeout: 20
    events:
      - httpApi:
          path: /v2/vision
          method: post

resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET}
      DeletionPolicy: Delete